# Application specific values available anywhere
# Loaded in /config/initializers/load_app_config.rb

site_display_name: chirp.cantl.in
default_title: chirp.cantl.in

twitter_consumer_key: foo
twitter_consumer_secret: bar
twitter_request_uri: http://api.twitter.com # Omit trailing slash
twitter_search_uri: http://search.twitter.com
twitter_oauth_endpoint: /oauth/authenticate # 'Sign in with Twitter'
# twitter_oauth_endpoint: /oauth/authorize # Regular OAuth
twitter_users_per_page: 20

twitter_method_paths:
  verify_credentials: /1/account/verify_credentials.json
  get_following: /1/statuses/friends.json
  get_followed_by: /1/statuses/followers.json
  unfollow: /1/friendships/destroy.json
  follow: /1/friendships/create.json
  search: /search.json?lang=en&rpp=100

# Rails.env

development:
  root_uri: http://localhost:3001/
  twitter_callback_uri: http://localhost:3001/callback

test:
  root_uri: http://localhost:3001/
  twitter_callback_uri: http://localhost:3001/callback

production:
  root_uri: http://chirp.cantl.in/
  twitter_callback_uri: http://chirp.cantl.in/callback