# Application specific values available anywhere
# Loaded in /config/initializers/load_app_config.rb

# global:
 
site_display_name: chirp.cantl.in
default_title: chirp.cantl.in

twitter_consumer_key: kMHmlN085Y6n4NMK45DpAw
twitter_consumer_secret: ePBglnJcHHlEmTH907pJRBkqOyMai0l2RVQ8kFwmc
twitter_api_uri: http://api.twitter.com # Omit trailing slash
twitter_oauth_endpoint_uri: http://api.twitter.com # Omit trailing slash

development:
  twitter_callback_uri: http://localhost:3001/callback

test:
  twitter_callback_uri: http://localhost:3001/callback

production:
  twitter_callback_uri: http://chirp.cantl.in/callback
